### ISSUE TITLE
General: how to deal with OGC CITE tests

### ISSUE THREAD

**Issue by thijsbrentjens** [inspire-eu-validation/ats-download-predefined-wfs#17]
Many requirements of Predefined Download services by WFS are requirements on general WFS conformance classes. The WFS standard describes tests for this in Annex A. The OGC CITE programme offers conformance testing for these classes. Is it sufficient for the ATS to refer to WFS/FES Annex A (the conformance class definitions) and refer to the OGC CITE tests?

**Comment by ilkkarinne** [comment]
Yes, I think the references to the ATSes within the OGC standards (WFS 2.0) and FES (2.0) are sufficient here. The CITE tests need not be referred here, it's the ETS level issue of which test implementations to use.
