### ISSUE TITLE
Numbering of test cases jumps from A.04 to A.06...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-download-predefined-wfs#18]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Numbering of test cases jumps from A.04 to A.06
# Proposed Change

Update numbering of test cases

**Comment by thijsbrentjens** [comment]
Agreed. To do after processing all ATS comments.
