### ISSUE TITLE
Consider if the prerequisites should be mentioned ...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-download-predefined-wfs#19]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Consider if the prerequisites should be mentioned in each test since they have to be tested anyway.
# Proposed Change

Remove the references to the OGC test or add them also to the other ATS (e.g. WMS, WMTS). In any case, do it in the same way for all ATS.

**Comment by cportele** [comment]
Addressed by https://github.com/inspire-eu-validation/ats-cross-cutting/issues/9

**Comment by cportele** [comment]
Status changed to "wontfix" as inspire-eu-validation/ats-cross-cutting#9 will implement this consistently.
