### ISSUE TITLE
A.04 and the following

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-download-predefined-wfs#27]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Prerequisites: A.01 already contains the both mentioned OGC WFS tests.
# Proposed Change

Remove the redundant test cases.

**Comment by cportele** [comment]
Proposed resolution:
- Implement proposed change

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
